# Generated by Django 3.1.7 on 2021-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_picture_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='id',
        ),
        migrations.AddField(
            model_name='picture',
            name='wo_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
